### ISSUE TITLE
ValueError: could not convert string to float: 'Amsterdam'

### ISSUE THREAD

**Issue by phuongpt3005** [Mohd-Abrar/Hotel-price-prediction#1]
![Screenshot from 2023-08-01 00-22-38](https://github.com/Mohd-Abrar/Hotel-price-prediction/assets/100830297/d7e4e93b-9922-4d78-8157-b3d8a862354a)
hello guy
I have a issue, can you help me fix it ?

**Comment by Mohd-Abrar** [comment]
Sure. Its may be of version issue. Try the following

sns.countplot(x=df['City'].sort_values() , palette = colors )

for i,v in enumerate(df['City'].value_counts().sort_index()):
    plt.text(x = i , y = v + 100, s = v , ha = 'center')

**Comment by phuongpt3005** [comment]
yeah it work
Thank you so much

**Comment by Mohd-Abrar** [comment]
Great!
